import { Producto } from '../interfaces/Producto'

export const productos: Producto[] = [
  {
    id: 1,
    nombre: 'Besitos',
    imagen: '/img/Besitos.png',
    descripcion: 'Dulce tradicional iqueño',
    precio: 8.00,
    categoria: 'Postres',
    ingredientes: 'Harina, azúcar, huevos, esencia de vainilla, mantequilla',
  },
  {
    id: 2,
    nombre: 'Paciencia',
    imagen: '/img/Paciencia.png',
    descripcion: 'Postre artesanal de la región',
    precio: 10.00,
    categoria: 'Postres',
    ingredientes: 'Manjar blanco, galleta molida, coco rallado, azúcar, canela',
  },
  {
    id: 3,
    nombre: 'Rosquitas',
    imagen: '/img/Rosquitas.png',
    descripcion: 'Rosquitas tradicionales',
    precio: 6.00,
    categoria: 'Postres',
    ingredientes: 'Harina, anís, mantequilla, huevos, azúcar, levadura',
  },
  {
    id: 4,
    nombre: 'Revolución',
    imagen: '/img/Revolucion.png',
    descripcion: 'Dulce típico iqueño',
    precio: 7.00,
    categoria: 'Postres',
    ingredientes: 'Dulce de camote, clavo de olor, canela, azúcar, harina',
  },
  {
    id: 5,
    nombre: 'Pan dulce',
    imagen: '/img/PanDulce.png',
    descripcion: 'Pan dulce artesanal',
    precio: 12.00,
    categoria: 'Panadería',
    ingredientes: 'Harina, mantequilla, huevos, leche, azúcar, levadura, pasas',
  },
  {
    id: 6,
    nombre: 'Camisón',
    imagen: '/img/Camison.png',
    descripcion: 'Postre tradicional de Ica',
    precio: 15.00,
    categoria: 'Postres',
    ingredientes: 'Harina, huevos, leche, mantequilla, azúcar, esencia de vainilla',
  },
  {
    id: 7,
    nombre: 'Mantecadas',
    imagen: '/img/hero-products.png',
    descripcion: 'Galletas mantecosas tradicionales',
    precio: 8.00,
    categoria: 'Galletas',
    ingredientes: 'Harina, mantequilla, azúcar, huevos, esencia de vainilla',
  },
  {
    id: 8,
    nombre: 'Polvorones',
    imagen: '/img/hero-products.png',
    descripcion: 'Polvorones artesanales peruanos',
    precio: 7.00,
    categoria: 'Galletas',
    ingredientes: 'Harina, manteca, azúcar impalpable, canela, nuez molida',
  },
  {
    id: 9,
    nombre: 'Alfajores',
    imagen: '/img/hero-products.png',
    descripcion: 'Alfajores con manjar blanco',
    precio: 9.00,
    categoria: 'Galletas',
    ingredientes: 'Harina, maicena, mantequilla, manjar blanco, coco rallado',
  },
  {
    id: 10,
    nombre: 'Torta de Chocolate',
    imagen: '/img/hero-products.png',
    descripcion: 'Torta húmeda de chocolate',
    precio: 25.00,
    categoria: 'Pasteles',
    ingredientes: 'Chocolate, harina, huevos, mantequilla, azúcar, leche, cocoa',
  },
  {
    id: 11,
    nombre: 'Tres Leches',
    imagen: '/img/hero-products.png',
    descripcion: 'Pastel bañado en tres leches',
    precio: 22.00,
    categoria: 'Pasteles',
    ingredientes: 'Harina, huevos, leche condensada, leche evaporada, crema de leche, vainilla',
  },
  {
    id: 12,
    nombre: 'Selva Negra',
    imagen: '/img/hero-products.png',
    descripcion: 'Torta Selva Negra con cereza',
    precio: 28.00,
    categoria: 'Pasteles',
    ingredientes: 'Chocolate, crema batida, cerezas, harina, huevos, mantequilla, licor',
  },
  {
    id: 13,
    nombre: 'Empanadas',
    imagen: '/img/hero-products.png',
    descripcion: 'Empanadas artesanales horneadas',
    precio: 10.00,
    categoria: 'Panadería',
    ingredientes: 'Harina, mantequilla, huevos, relleno de manjar blanco o dulce de membrillo',
  },
]
